server:
  port: 8082
spring:
  application:
    name: micro2
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  server:
    renewalPercentThreshold: 0.9

